### ISSUE TITLE
각 목차를 누르면 404 error!?

### ISSUE THREAD

**Issue by haksungjang** [ncsoft/osc-enterprise-ko#1]
먼저, 유용한 자료 공유해주셔서 정말 감사합니다.
이슈는 README > 각 목차를 누르면 > 404 error 가 발생합니다. ^^

**Comment by dasomhan** [comment]
경로 오류였으며, 현재는 수정되었습니다 ^^

**Comment by dasomhan** [comment]
경로 오류를 수정하였습니다. ^^
