### ISSUE TITLE
링크 오류 

### ISSUE THREAD

**Issue by haksungjang** [ncsoft/osc-enterprise-ko#2]
Chapter 13_Open Source Audits in Merger and Acquisition Transactions.md > 

"7. 인수 대상 회사에서의 감사 준비
본인의 소스코드에 어떤 오픈소스가 포함되어 있는지 알아야 함
컴플라이언스에 적극적으로 참여해야 함
오픈소스를 보안취약점이 개선된 최신 소프트웨어 버전을 사용해야 함
OpenChain Conformant 웹 사이트에서 현재의 컴플라이언스 준수 상태를 체크하는 것을 권장함"

에서 "OpenChain Conformant 웹 사이트" 링크를 누르면 404 에러 발생합니다.

**Comment by dasomhan** [comment]
URL 수정했습니다. 제보 감사합니다~
